Repository manishcms/git-test, pull requests merged in 2022-04, with the labels that each got.

#4 file 10 content added
  test-10.txt
Labels: documentation

#3 file 15 new added
  test15.txt
Labels: enhancement

#2 my new text added
  test.txt
Labels: enhancement

#5 change in test-9
  test-9.txt
Labels: bug

#9 changes by vaibhav
  test-vaibhav.txt
Labels: bug
